
name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create true
          poetry lock
          poetry install --no-interaction --no-ansi
      - name: Create executable file with pyinstaller and zip
        run: |
          poetry run pyinstaller aw_watcher_virtualdesktop/__main__.py --name aw_watcher_viratualdesktop
          pushd dist
          Compress-Archive -Path sample  -DestinationPath aw_watcher_virtualdesktop.zip
          popd
      - name: Upload a executable file to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/sample-windows.zip

